apiVersion: v1
kind: Service
metadata:
  namespace: demo-app
  name: demo-app
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
  - port: 80
    name: http
    targetPort: 5678
  # - port: 443
  #   name: https
  #   targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-app
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: hashicorp/http-echo
        args:
        - "-text=echo1"
        imagePullPolicy: Always
        ports:
        - containerPort: 5678
          protocol: TCP
