apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __K8_APP_NAMESPACE__
  name: __K8_DOCKER_APP_NAME__
spec:
  selector:
    matchLabels:
      app: __K8_DOCKER_APP_NAME__
  replicas: 1
  template:
    metadata:
      labels:
        app: __K8_DOCKER_APP_NAME__
    spec:
      containers:
