        - name: dind-daemon 
          image: docker:18.09.0-dind
          resources: 
              requests: 
                  cpu: 20m 
                  memory: 512Mi
          securityContext: 
              privileged: true 
          volumeMounts: 
            - name: docker-graph-storage 
              mountPath: /var/lib/docker 
      volumes: 
        - name: docker-graph-storage 
          emptyDir: {}
