apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: __K8_APP_NAMESPACE__
  name: test-cron-job
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 7
  successfulJobsHistoryLimit: 5
  suspend: false
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
          - name: test-cron-job
            image: __K8_APP_IMAGE__
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
