apiVersion: v1
kind: Service
metadata:
  namespace: demo-app
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-app
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: prequod/inspire-me:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
