apiVersion: v1
kind: Service
metadata:
  namespace: __K8_APP_NAMESPACE__
  name: __K8_APP_NAME__
spec:
  type: LoadBalancer
  selector:
    app: __K8_APP_NAME__
  ports:
  - port: 80
    name: http
    targetPort: __K8_APP_PORT__
  # - port: 443
  #   name: https
  #   targetPort: __K8_APP_PORT__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __K8_APP_NAMESPACE__
  name: __K8_APP_NAME__
spec:
  selector:
    matchLabels:
      app: __K8_APP_NAME__
  replicas: 1
  template:
    metadata:
      labels:
        app: __K8_APP_NAME__
    spec:
      containers:
      - name: __K8_APP_NAME__
        image: __K8_APP_IMAGE__
        imagePullPolicy: Always
        env:
        - name: SECRET_TEST
          valueFrom:
            secretKeyRef:
              name: pandoras-box
              key: test-secret
        ports:
        - containerPort: __K8_APP_PORT__
          protocol: TCP
