apiVersion: v1
kind: Service
metadata:
  namespace: "K8_APP_NAMESPACE"
  name: "K8_APP_NAME"
spec:
  type: LoadBalancer
  selector:
    app: "K8_APP_NAME"
  ports:
  - port: 80
    name: http
    targetPort: "K8_APP_PORT"
  # - port: 443
  #   name: https
  #   targetPort: "K8_APP_PORT"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "K8_APP_NAMESPACE"
  name: "K8_APP_NAME"
spec:
  selector:
    matchLabels:
      app: "K8_APP_NAME"
  replicas: 1
  template:
    metadata:
      labels:
        app: "K8_APP_NAME"
    spec:
      containers:
      - name: "K8_APP_NAME"
        image: "K8_APP_IMAGE"
        imagePullPolicy: Always
        ports:
        - containerPort: K8_APP_PORT
          protocol: TCP
